### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by jcbhmr** [ziglang/release-cutter#5]
Hello! 👋

I'd like to use, modify, and create derivative works from the code in this repository. I am unsure whether or not I am allowed to do so under the default of "no license".

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.

-- https://choosealicense.com/no-permission/

I don't know whether such a "no license" is intentional to reserve copyright on the code or if it's just that no LICENSE file has been added to this repository.

Or maybe I'm being dense and there's already a license specified somewhere and I just can't find it lol 😵

cc @andrewrk

**Comment by andrewrk** [comment]
which file do you want to use, modify, and create derivative works from?

**Comment by jcbhmr** [comment]
The big ./script release script in particular.
